name: gxt_native
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '3.0.2'

dependencies:
  webf: ^0.15.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: false
